# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >
  The wine-cellar-backend application

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 100

Parameters:
  DBUSER:
    Type: String
    Description: the user database
    Default: postgres # local mode only

  DBPWD:
    Type: String
    Description: the user password
    Default: s3cretp4ss # local mode only

  DBHOST:
    Type: String
    Description: the db host
    Default: 127.0.0.1 # local mode only

  DBPORT:
    Type: Number
    Description: the db port
    Default: 5432

  DBNAME:
    Type: String
    Description: the db host
    Default: postgres

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: in src/main.ts
  NestServerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/main.handler
      Description: Runs the full NestJs api.
      Environment:
        Variables:
          DB_USER: !Ref DBUSER
          DB_PWD: !Ref DBPWD
          DB_HOST: !Ref DBHOST
          DB_PORT: !Ref DBPORT
          DB_NAME: !Ref DBNAME
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{all+}
            Method: ANY
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - AWSLambdaBasicExecutionRole

  # Shared layer with Lambda runtime dependencies
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain

Outputs:
  WebEndpoint:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
